import type { NextPage } from "next";
import dynamic from "next/dynamic";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import withLoading from "../Hoc/Loading";
import { useDispatch } from "react-redux";
import { useAppSelector, useAppDispatch } from "../hooks/redux-hooks";
import ApiCall from "../infrastructure/services/axios";
import { IError } from "../infrastructure/interface";
const CharacterCard = dynamic(
  () => import("../components/specifics/characterCard")
);
const Error = dynamic(() => import("../components/specifics/error"));
const Dropdown = dynamic(() => import("../components/specifics/dropdown"));
import {
  setCharacter,
  clearCharacter,
  selectCharacter,
} from "../store/features/charactersSlice";
import { RootState } from "../store/index";

export const getServerSideProps = async () => {
  let result = null;
  let error: IError = {
    message: "",
    statusCode: 0,
  };
  try {
    await ApiCall({
      url: "character/?page=1&name=&status=&gender=&species",
    })
      .then((res) => {
        result = res;
      })
      .catch(({ status, statusText }) => {
        error.statusCode = status;
        error.message = statusText;
      });
    console.log("result---", result);
    return {
      props: {
        characters: result,
      },
    };
  } catch {
    return {
      props: {
        characters: result,
        error,
      },
    };
  }
};
const Home: NextPage = (props) => {
  const { characters, errorCode, error }: any = props;
  const dispatch = useAppDispatch();
  const test: any = useAppSelector(selectCharacter);
  const [name, setName] = useState("a");
  if (error)
    return <Error statusCode={error.statusCode} message={error.message} />;
  return (
    <div className={"col bg-white mx-3 p-3 rounded-3"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="col d-flex">
        {/* <Dropdown /> */}
        {/* <div>
          <Dropdown
            label={"React Select"}
            placeholder="Pick one"
            options={[
              { value: "Rock" },
              { value: "Paper" },
              { value: "Scissors" },
            ]}
          />
          <span style={{ display: "inline-block", width: 20 }} />
          <Dropdown
            label="React Multiple Select"
            placeholder="Pick some"
            options={[
              { value: "Rock" },
              { value: "Paper" },
              { value: "Scissors" },
            ]}
            multiple
          />
        </div> */}
        <div className="col row">
          {characters?.results?.map((character: any) => (
            <div className="col-md-4 my-2" key={character.id}>
              <CharacterCard {...character} />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
