import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import withLoading from "../Hoc/Loading";
import { useDispatch } from "react-redux";
import { useAppSelector, useAppDispatch } from "../hooks/redux-hooks";
import ApiCall from "../infrastructure/services/axios";
import CharacterCard from "../components/specifics/characterCard";
import {
  setCharacter,
  clearCharacter,
  selectCharacter,
} from "../store/features/charactersSlice";
import { RootState } from "../store/index";
export const getServerSideProps = async () => {
  let result = null;
  await ApiCall({
    url: "character/?page=1&name=&status=&gender=&species",
  })
    .then((res) => {
      result = res;
    })
    .catch((err) => console.log("apo call", err));
  console.log("result---", result);
  return {
    props: {
      characters: result,
    },
  };
};
const Home: NextPage = (props) => {
  const { characters }: any = props;
  const dispatch = useAppDispatch();
  const test: any = useAppSelector(selectCharacter);
  const [name, setName] = useState("a");
  return (
    <div className={"col bg-white mx-3 p-3 rounded-3"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="col d-flex">
        {/* {name}
          {test && test.name ? test.name : "Hello Guest"}
          <div>
            <Link href="/characters">
              <a>characters</a>
            </Link>
          </div>
          <div>
            <Link href="/locations">
              <a>location</a>
            </Link>
          </div>
          <div>
            <Link
              href={{
                pathname: "/characters/[id]",
                query: { id: "test" },
              }}
            >
              <a>characters/detail</a>
            </Link>
          </div>
          <div>
            <Link href="/characters/test">Go to pages/characters/[id]</Link>
          </div> */}
        <div className="col row">
          {characters?.results?.map((character: any) => (
            <a
              className="col-md-4 my-2"
              href={`/characters/${character.id}`}
              key={character.id}
            >
              <CharacterCard {...character} />
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
